* YACIL
Yet another C Introspection library, there are a plethora of ways to get some form of reflection working in C.
However most methods are a pain to setup, require lots of instrumented code and are slow as hell. 
** Solution
    To provide a generic way to do a form of introspection we rely on the debug information generated by the compiler.
    We parse this information ourselves directly into a YACIL module on which we can perform queries to find type information.
    This information can then be used to build applications which can rely on the debug type information to connect various modules.
** Feature list
    A quick summation of the features and scope I have for YACIL
    - [ ] Parsing PDB files
    - [ ] Parsing DSYM files
    - [ ] Parsing DWARF/ELF files
    - [X] Provide Queries for Enum
    - [ ] Provide Queries for Simple types
    - [ ] Provide Queries for Structs
    - [ ] Provide Queries for Array types
    - [ ] Provide Queries for Classes
    - [ ] Provide Queries for Functions
    - [ ] Provide Queries for Membership functions
    - [ ] Provide Queries for Pointer types

